"""empty message

Revision ID: 338467f3eef5
Revises: b160b583a6aa
Create Date: 2020-02-20 20:05:26.137637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338467f3eef5'
down_revision = 'b160b583a6aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('id_num', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'id_num')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###
